### PR TITLE
Error status guidelines alignment

### PR DESCRIPTION
**Pull request by monamok**
Related to the [issue#13](https://github.com/camaraproject/OTPvalidationAPI/issues/13)
It includes error status code alignment. I also figured that Meeting minutes that were agreed in Number Verification were not updated here so I also copied that last reviewed version from that repo.

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
Hello
Look good for me.
One very small point... we have changed in the Carrier Billing API the status pattern to:
  pattern: '^[4-5][0-9]{2}$'

Here we have min/max.

I'm fine with both... but perhaps we can have an update in the design guidelines to have only one way.

**Comment by bigludo7** [comment]
Sorry @monamok I miss the discussion there:  https://github.com/camaraproject/WorkingGroups/issues/143

It's up to us - Carrier Billing team - to change the status datatype ;)

**Comment by monamok** [comment]
@bigludo7 I adjusted the range to 400-599.

**Comment by monamok** [comment]
Kindly reminder: @DT-DawidWroblewski could you please review and merge this PR?

**Pull request merged**
